"""
Build the M2 (mechanistic Stage-2 prediction) block for all 7 candidate KD
models, for the calibration set and both test splits generated by
gen_calibration_extrapolation.py.

Reuses, verbatim, two pieces of EXISTING code (no new kinetic equations):
  - M0-M5 rhs functions: copied from gen_all.py (its own model set, already
    used in the calibration/M2M analysis). These use the TRUE/nominal kinetic
    parameters (A3=10, A4=20, Ea3=50000, Ea4=55000) directly, exactly as
    gen_all.py does -- no curve_fit for M0-M5, that's the existing convention.
  - M6 rhs: copied from Data Generation.py / KD_fit.py's stage2_mis (the
    paper's own published misspecified case: no C/F reaction, order-1 in D).
    Its parameters ARE estimated via curve_fit, exactly as in Data
    Generation.py's model_stage2_mis + curve_fit call, but fit ONCE on the
    100 calibration batches only, then frozen and reused unchanged for the
    two test splits (no refitting on test data -> no leakage).

For every batch and every model: IC = that batch's own X2 at t=0 (first
timepoint), T2 = that batch's own known operating temperature. Neither is
"future" information -- t=0 is the starting state and T2 is a fixed batch
set-point, both known before the Stage-2 trajectory unfolds. No X2 timepoint
after t=0 is ever used to build M2.
"""
import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import curve_fit
import warnings
warnings.filterwarnings('ignore')

R = 8.314
A3_true, A4_true, Ea3_true, Ea4_true = 10.0, 20.0, 50000.0, 55000.0
species = ['A', 'B', 'C', 'D', 'E', 'F']

# ============================================================
# M0-M5: rhs copied verbatim from gen_all.py
# ============================================================
def m_correct(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v)); k4 = A4 * np.exp(-Ea4 / (R * T2v))
    return [0, -k3*CB*CD**2, -k4*CC*CD**2, -2*k3*CB*CD**2-2*k4*CC*CD**2, k3*CB*CD**2, k4*CC*CD**2]

def m_no_side(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v))
    return [0, -k3*CB*CD**2, 0, -2*k3*CB*CD**2, k3*CB*CD**2, 0]

def m_order1_D(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v)); k4 = A4 * np.exp(-Ea4 / (R * T2v))
    return [0, -k3*CB*CD, -k4*CC*CD, -2*k3*CB*CD-2*k4*CC*CD, k3*CB*CD, k4*CC*CD]

def m_wrong_Ea4(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v)); k4 = A4 * np.exp(-Ea3 / (R * T2v))  # Ea3 used for k4
    return [0, -k3*CB*CD**2, -k4*CC*CD**2, -2*k3*CB*CD**2-2*k4*CC*CD**2, k3*CB*CD**2, k4*CC*CD**2]

def m_lumped(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v))
    rate = k3 * (CB + CC) * CD**2
    return [0, -k3*CB*CD**2, -k3*CC*CD**2, -2*rate, k3*CB*CD**2, k3*CC*CD**2]

def m_no_D(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v)) * 1e6; k4 = A4 * np.exp(-Ea4 / (R * T2v)) * 1e6
    return [0, -k3*CB, -k4*CC, -2*k3*CB-2*k4*CC, k3*CB, k4*CC]

# M6: rhs copied verbatim from Data Generation.py's stage2_mis
def m_author_mis(y, t, T2v, A3, A4, Ea3, Ea4):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3 * np.exp(-Ea3 / (R * T2v))
    dCB = -k3 * CB * CD
    dCD = -2 * k3 * CB * CD
    dCE = k3 * CB * CD
    return [0, dCB, 0, dCD, dCE, 0]

MODELS = {
    'M0_correct':   (m_correct,     'Full mechanism (correct)',              False),
    'M1_no_side':   (m_no_side,     'Deleted side reaction C+2D->F',         False),
    'M2_order1_D':  (m_order1_D,    'Wrong order in D (1st not 2nd)',        False),
    'M3_wrong_Ea4': (m_wrong_Ea4,   'Wrong activation energy Ea4=Ea3',       False),
    'M4_lumped_EF': (m_lumped,      'Lumped E+F into one product',           False),
    'M5_no_D':      (m_no_D,        'Ignored D dependence (D in excess)',    False),
    'M6_author_mis':(m_author_mis,  'Author published mis-model (curve_fit)',True),
}

# ============================================================
# Load the three datasets generated last turn
# ============================================================
FILES = {
    'calibration': 'DG_calibration.xlsx',
    'within_domain': 'DG_test_within_domain.xlsx',
    'extrapolation': 'DG_test_extrapolation.xlsx',
}
X2 = {k: pd.read_excel(f, sheet_name='X2') for k, f in FILES.items()}


def n_timepoints(df):
    return max(int(c.split('_t')[1]) for c in df.columns if c.startswith('A_t'))


def get_IC_T2(df, row):
    ic = np.array([df.loc[row, f'{s}_t1'] for s in species], dtype=float)
    T2v = float(df.loc[row, 'T2'])
    return ic, T2v


def time_grid_seconds(n_pts):
    return np.arange(n_pts) * 15.0  # sample_interval=0.25 min = 15 s, t1 -> t=0


def simulate_M2(df, rhs, params):
    """Integrate rhs for every batch (row) in df, using that batch's own
    X2(t=0) as IC and its own T2. Returns array (n_batches, 6, n_pts)."""
    n_pts = n_timepoints(df)
    tgrid = time_grid_seconds(n_pts)
    n = len(df)
    out = np.zeros((n, 6, n_pts))
    for i in range(n):
        ic, T2v = get_IC_T2(df, i)
        sol = odeint(rhs, ic, tgrid, args=(T2v,) + params)
        out[i] = sol.T
    return out, n_pts


def to_dataframe(arr, df_src, n_pts):
    cols = {'CD0': df_src['CD0'].values, 't2_final': df_src['t2_final'].values, 'T2': df_src['T2'].values}
    for j, s in enumerate(species):
        for k in range(n_pts):
            cols[f'{s}_t{k+1}'] = arr[:, j, k]
    return pd.DataFrame(cols)


# ============================================================
# M6 parameter estimation: curve_fit on the 100 CALIBRATION batches only
# ============================================================
def fit_M6_params():
    df = X2['calibration']
    n_pts = n_timepoints(df)
    tgrid = time_grid_seconds(n_pts)
    n = len(df)
    ics = np.array([get_IC_T2(df, i)[0] for i in range(n)])
    T2s = np.array([get_IC_T2(df, i)[1] for i in range(n)])
    y_observed = np.array([[df.loc[i, f'{s}_t{k+1}'] for s in species for k in range(n_pts)] for i in range(n)]).ravel()

    def model_flat(_, A3, A4, Ea3, Ea4):
        preds = np.zeros((n, 6, n_pts))
        for i in range(n):
            sol = odeint(m_author_mis, ics[i], tgrid, args=(T2s[i], A3, A4, Ea3, Ea4))
            preds[i] = sol.T
        return preds.reshape(n, -1).ravel()

    p0 = [A3_true, A4_true, Ea3_true, Ea4_true]
    fitted, _ = curve_fit(model_flat, np.zeros_like(y_observed), y_observed, p0=p0,
                           maxfev=10000, bounds=([0, 0, 0, 0], [100, 100, np.inf, np.inf]))
    return tuple(fitted)  # (A3, A4, Ea3, Ea4)


print("Fitting M6 (author misspecified model) kinetic parameters via curve_fit on the 100 calibration batches...")
M6_params = fit_M6_params()
print(f"  M6 fitted [A3, A4, Ea3, Ea4] = {np.round(M6_params, 4)}  (A4, Ea4 are inert -- unused in stage2_mis dynamics)")
print(f"  True/nominal                = [{A3_true}, {A4_true}, {Ea3_true}, {Ea4_true}]")

TRUE_PARAMS = (A3_true, A4_true, Ea3_true, Ea4_true)

# ============================================================
# Generate M2 for all 7 models x 3 datasets, save, sanity-check
# ============================================================
results = {}
sanity_rows = []
for split_name, df in X2.items():
    for model_name, (rhs, desc, uses_fit) in MODELS.items():
        params = M6_params if uses_fit else TRUE_PARAMS
        arr, n_pts = simulate_M2(df, rhs, params)
        out_df = to_dataframe(arr, df, n_pts)
        results[(split_name, model_name)] = out_df

        nan_flag = np.isnan(arr).any()
        neg_flag = (arr < -1e-6).any()
        huge_flag = (arr > 1e6).any()
        sanity_rows.append({
            'split': split_name, 'model': model_name, 'n_batches': len(df), 'n_timepoints': n_pts,
            'any_nan': nan_flag, 'any_negative': neg_flag, 'any_huge': huge_flag,
            'min_val': arr.min(), 'max_val': arr.max(),
        })

sanity_df = pd.DataFrame(sanity_rows)
print("\n===== M2 SANITY CHECKS (all splits x all models) =====")
print(sanity_df.to_string(index=False))

fail = sanity_df[sanity_df['any_nan'] | sanity_df['any_negative'] | sanity_df['any_huge']]
if len(fail):
    print(f"\n*** {len(fail)} model/split combinations FAILED sanity checks ***")
    print(fail.to_string(index=False))
else:
    print("\nAll model/split combinations passed: no NaNs, no negatives, no absurd values.")

# batch-order / column-order / timepoint-count cross-check against X2
print("\n===== STRUCTURE CROSS-CHECK vs X2 =====")
for split_name, df in X2.items():
    ref_n_pts = n_timepoints(df)
    m0 = results[(split_name, 'M0_correct')]
    same_len = len(m0) == len(df)
    same_pts = n_timepoints(m0) == ref_n_pts
    same_cols_order = list(m0.columns) == list(df.columns)
    print(f"{split_name:<15} batches match={same_len}  timepoints match={same_pts} ({ref_n_pts})  column order match={same_cols_order}")

# ============================================================
# Save one file per candidate model, each with 3 sheets (one per split)
# ============================================================
for model_name in MODELS:
    fname = f"M2_{model_name}.xlsx"
    with pd.ExcelWriter(fname) as writer:
        for split_name in X2:
            results[(split_name, model_name)].to_excel(writer, sheet_name=split_name, index=False)
    print(f"Saved {fname}  (sheets: {list(X2.keys())})")

# ============================================================
# Representative trajectory plots: X2 measured vs M2 (M0 correct, M6 misspecified)
# one batch each from calibration / within-domain / extrapolation
# ============================================================
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, axes = plt.subplots(3, 3, figsize=(15, 11))
split_batch = {'calibration': 0, 'within_domain': 0, 'extrapolation': 0}
plot_species = ['B', 'D', 'E']  # a reactant, the other reactant, the target product

for row, (split_name, batch_i) in enumerate(split_batch.items()):
    df_x2 = X2[split_name]
    n_pts = n_timepoints(df_x2)
    tgrid = time_grid_seconds(n_pts)
    m0 = results[(split_name, 'M0_correct')]
    m6 = results[(split_name, 'M6_author_mis')]
    for col, sp in enumerate(plot_species):
        ax = axes[row, col]
        x2_vals = [df_x2.loc[batch_i, f'{sp}_t{k+1}'] for k in range(n_pts)]
        m0_vals = [m0.loc[batch_i, f'{sp}_t{k+1}'] for k in range(n_pts)]
        m6_vals = [m6.loc[batch_i, f'{sp}_t{k+1}'] for k in range(n_pts)]
        ax.plot(tgrid, x2_vals, 'ko-', label='X2 measured', markersize=4)
        ax.plot(tgrid, m0_vals, 'g^--', label='M0 correct', markersize=4)
        ax.plot(tgrid, m6_vals, 'rs--', label='M6 misspecified', markersize=4)
        ax.set_title(f"{split_name} batch {batch_i}, species {sp}  (T2={df_x2.loc[batch_i,'T2']:.1f} K)", fontsize=9)
        ax.set_xlabel('time [s]'); ax.set_ylabel('conc [mol/m3]')
        ax.grid(alpha=0.3)
        if row == 0 and col == 0:
            ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig('M2_vs_X2_representative.png', dpi=140, facecolor='white')
print("\nSaved M2_vs_X2_representative.png")
