"""
Regenerate data with the CORRECTED generator (Data_Generation_corrected.py,
sigma1/sigma2 taken verbatim from the author's notebook) and compare
statistically against the real author Excel files: X1.xlsx/X2.xlsx/M2.xlsx/
Y.xlsx (case i, well-specified) and X1_mis.xlsx/X2_mis.xlsx/M2_mis.xlsx/
Y_mis.xlsx (case ii, misspecified, generated by the author's own notebook).

Does not modify Data Generation.py, the corrected generator file, or any
Excel file. Only reads existing Excel files and writes NEW comparison
output (this script's own console output + one plot).
"""
import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import curve_fit
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.insert(0, '.')
from Data_Generation_corrected import (stage1_drift, stage1_noise, stage2_drift, stage2_noise,
                                        one_sde_simulation, discrete_trajectories, R)

N = 100
GLOBAL_SEED = 10  # same convention as Data Generation.py, for a fair comparison

# =====================================================================
# STEP 1: regenerate N=100 case-(i) batches with the corrected generator
# =====================================================================
print("Regenerating 100 batches (case i, well-specified) with corrected sigma1/sigma2...")
np.random.seed(GLOBAL_SEED)
all_stage1, all_stage2, all_params = [], [], []
for i in range(N):
    (t1v, sol1), (t2v, sol2), params = one_sde_simulation(data_type="training")
    all_stage1.append((t1v, sol1)); all_stage2.append((t2v, sol2)); all_params.append(params)

disc1, disc2 = discrete_trajectories(all_stage1, all_stage2)
min_pts = min(len(d[0]) for d in disc2)
print(f"  min stage-2 discretized points across the 100 batches: {min_pts}")

species = ['A', 'B', 'C', 'D', 'E', 'F']
CA0v = np.array([p['CA0_sample'] for p in all_params])
CD0v = np.array([p['CD0_sample'] for p in all_params])
T1v = np.array([p['T1'] for p in all_params])
T2v = np.array([p['T2'] for p in all_params])
t1v_ = np.array([p['t1_seconds'] for p in all_params])
t2v_ = np.array([p['t2_seconds'] for p in all_params])

X2g_final = np.array([disc2[i][1][min_pts - 1] for i in range(N)])
Yg = X2g_final[:, 4] / X2g_final.sum(axis=1) * 100

# =====================================================================
# STEP 2: load real case-(i) Excel files and compare
# =====================================================================
X1a = pd.read_excel('X1.xlsx'); X2a = pd.read_excel('X2.xlsx')
Ya = pd.read_excel('Y.xlsx'); M2a = pd.read_excel('M2.xlsx')
n_author_pts = X2a.shape[1] // 6

print("\n===== CASE (i): OPERATING CONDITIONS: author vs corrected generator =====")
print(f"{'var':<8}{'author mean':>14}{'author sd':>12}{'author min':>12}{'author max':>12}   |  "
      f"{'gen mean':>10}{'gen sd':>10}{'gen min':>10}{'gen max':>10}")
for name, av, gv in [('CA0', X1a['CA0'].values, CA0v), ('T1', X1a['T1'].values, T1v),
                     ('t1', X1a['t1'].values, t1v_ / 60), ('T2', M2a['T2'].values, T2v),
                     ('t2', M2a['t2'].values * 60, t2v_), ('D0', M2a['D0'].values, CD0v)]:
    print(f"{name:<8}{av.mean():>14.2f}{av.std(ddof=1):>12.2f}{av.min():>12.2f}{av.max():>12.2f}   |  "
          f"{gv.mean():>10.2f}{gv.std(ddof=1):>10.2f}{gv.min():>10.2f}{gv.max():>10.2f}")

print("\n===== CASE (i): FINAL-TIMEPOINT CONCENTRATIONS (mean +/- sd): author vs corrected generator =====")
for j, sp in enumerate(species):
    a_final = X2a[f'{sp}_{n_author_pts}'].values
    g_final = X2g_final[:, j]
    print(f"{sp}: author {a_final.mean():9.2f} +/- {a_final.std(ddof=1):7.2f}   "
          f"gen(corrected) {g_final.mean():9.2f} +/- {g_final.std(ddof=1):7.2f}")

print(f"\nY (E purity, %): author mean={Ya['E_pur'].mean():.2f} sd={Ya['E_pur'].std(ddof=1):.2f}  "
      f"min={Ya['E_pur'].min():.2f} max={Ya['E_pur'].max():.2f}   |  "
      f"gen mean={Yg.mean():.2f} sd={Yg.std(ddof=1):.2f} min={Yg.min():.2f} max={Yg.max():.2f}")

# Batch-to-batch variance-vs-time for species A (A doesn't react -> pure diffusion signature)
print("\n===== CASE (i): Var[A(t)] across batches at each of the 7 shared timepoints: author X2 vs corrected generator =====")
tgrid = np.arange(7) * 15.0
print(f"{'t[s]':<8}{'author Var(A)':>16}{'gen Var(A)':>14}")
for k in range(min(7, n_author_pts, min_pts)):
    va = X2a[f'A_{k+1}'].values.var(ddof=1)
    vg = np.array([disc2[i][1][k, 0] for i in range(N)]).var(ddof=1)
    print(f"{tgrid[k]:<8.0f}{va:>16.3f}{vg:>14.3f}")

# =====================================================================
# STEP 3: case (ii), misspecified -- regenerate via the SAME truth SDE +
# the notebook's misspecified stage2_ode + curve_fit, compare to *_mis.xlsx
# =====================================================================
print("\n\nRegenerating case (ii) (misspecified fit) with corrected sigma1/sigma2...")
np.random.seed(GLOBAL_SEED + 1)  # different draw, since author's notebook case ii is a separate run
all_stage1_ii, all_stage2_ii, all_params_ii = [], [], []
for i in range(N):
    (t1v, sol1), (t2v, sol2), params = one_sde_simulation(data_type="training")
    all_stage1_ii.append((t1v, sol1)); all_stage2_ii.append((t2v, sol2)); all_params_ii.append(params)
disc1_ii, disc2_ii = discrete_trajectories(all_stage1_ii, all_stage2_ii)
min_pts_ii = min(len(d[0]) for d in disc2_ii)

def stage2_ode_mis(y, t, T2, Ea3, Ea4, A3f, A4f):
    CA, CB, CC, CD, CE, CF = y
    k3 = A3f * np.exp(-Ea3 / (R * T2))
    dCB = -k3 * CB * CD
    dCD = -2 * k3 * CB * CD
    dCE = k3 * CB * CD
    return [0, dCB, 0, dCD, dCE, 0]

data_dict_list = []
for i, (tk2, sol2d) in enumerate(disc2_ii):
    data_dict_list.append(dict(T2=all_params_ii[i]['T2'], time=tk2, conc=sol2d))

def model_flat(_, Ea3, Ea4, A3f, A4f):
    preds = []
    for d in data_dict_list:
        sol = odeint(stage2_ode_mis, d['conc'][0], d['time'] * 60, args=(d['T2'], Ea3, Ea4, A3f, A4f))
        preds.append(sol.ravel())
    return np.concatenate(preds)

y_obs = np.concatenate([d['conc'].ravel() for d in data_dict_list])
fitted, _ = curve_fit(model_flat, np.zeros_like(y_obs), y_obs, p0=[50000, 55000, 10, 20],
                       maxfev=10000, bounds=([0, 0, 0, 0], [np.inf, np.inf, 100, 100]))
print(f"  fitted [Ea3,Ea4,A3,A4] = {np.round(fitted, 3)}")

X2g_final_ii = np.array([disc2_ii[i][1][min_pts_ii - 1] for i in range(N)])
Yg_ii = X2g_final_ii[:, 4] / X2g_final_ii.sum(axis=1) * 100

X1m = pd.read_excel('X1_mis.xlsx'); X2m = pd.read_excel('X2_mis.xlsx')
Ym = pd.read_excel('Y_mis.xlsx'); M2m = pd.read_excel('M2_mis.xlsx')
n_pts_m = X2m.shape[1] // 6

print("\n===== CASE (ii): FINAL-TIMEPOINT CONCENTRATIONS (mean +/- sd): author vs corrected generator =====")
for j, sp in enumerate(species):
    a_final = X2m[f'{sp}_{n_pts_m}'].values
    g_final = X2g_final_ii[:, j]
    print(f"{sp}: author {a_final.mean():9.2f} +/- {a_final.std(ddof=1):7.2f}   "
          f"gen(corrected) {g_final.mean():9.2f} +/- {g_final.std(ddof=1):7.2f}")

print(f"\nY (E purity, %): author mean={Ym['E_pur'].mean():.2f} sd={Ym['E_pur'].std(ddof=1):.2f}   |  "
      f"gen mean={Yg_ii.mean():.2f} sd={Yg_ii.std(ddof=1):.2f}")

# =====================================================================
# PLOT: overlay author vs corrected-generator distributions
# =====================================================================
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
for j, sp in enumerate(species):
    ax = axes[j // 3, j % 3]
    a_final = X2a[f'{sp}_{n_author_pts}'].values
    g_final = X2g_final[:, j]
    ax.hist(a_final, bins=15, alpha=0.6, label='author X2 (case i)', color='black', density=True)
    ax.hist(g_final, bins=15, alpha=0.6, label='corrected generator', color='#3E7C8C', density=True)
    ax.set_title(f'Species {sp}, final timepoint'); ax.legend(fontsize=7); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('corrected_vs_excel_case_i.png', dpi=130, facecolor='white')
print("\nSaved corrected_vs_excel_case_i.png")
