"""
Corrected two-stage batch reactor SDE generator.

This is NOT a modification of Data Generation.py -- that file is untouched.
This is a separate, standalone file with the diffusion coefficients fixed
to match the author's own notebook (simulation_two_stage_reactor (3).ipynb,
cells 3 and 5) exactly, instead of Data Generation.py's opt_sigma1/opt_sigma2
arrays (which came from calibration.py's "target 1% CV" calibration routine
-- a procedure the author's actual notebook never runs).

Source of truth (simulation_two_stage_reactor (3).ipynb, cell 5):
    def stage1_noise(y, t):
        return np.diag([0.75, 0.75, 0.25])
    def stage2_noise(y, t):
        return np.diag([0.25, 0.75, 0.25, 0.75, 0.75, 0.25])

Everything else here (parameter values, T1/T2/t1/t2 ranges, 5% CV on
CA0/CD0 initial-condition noise, dilution logic, stage1/stage2 drift
mechanisms, discretization convention noise_percentage=0.0035 /
sample_interval=0.25 min) was cross-checked against the same notebook and
already matched Data Generation.py -- only the two noise-diagonal arrays
below were wrong.

This file only defines the generator; it does not run anything or write
any data. No files are regenerated by importing/running this script beyond
what an explicit __main__ call below would do (kept minimal/inert).
"""
import numpy as np
import sdeint

# --- Parameters (unchanged from Data Generation.py / the author's notebook) ---
V1 = 0.1   # m3 (Stage 1 reactor volume)
V2 = 0.2   # m3 (Stage 2 reactor volume)

CA0 = 2000.0   # mol/m3 (A in stage 1)
CD0 = 1900.0   # mol/m3 (D in the solution added to stage 2)

A1, A2 = 28, 40      # s^-1
A3, A4 = 10, 20      # m^6/(mol^2*s)
Ea1_mean, Ea2_mean, Ea3_mean, Ea4_mean = 20000, 30000, 50000, 55000   # J/mol
CV = 0.01             # coefficient of variation for activation energies
R = 8.314             # J/(mol*K)

T1_range = (290, 310)
T2_range_training = (330, 370)
T2_range_testing = (362, 382)
t1_range = (350, 650)
t2_range = (100, 400)

# --- CORRECTED diffusion coefficients (author's notebook, cell 5, verbatim) ---
sigma1 = [0.75, 0.75, 0.25]                        # stage 1: A, B, C
sigma2 = [0.25, 0.75, 0.25, 0.75, 0.75, 0.25]       # stage 2: A, B, C, D, E, F


def stage1_drift(y, t, k1, k2):
    CA, CB, CC = y
    dCAdt = -k1 * CA
    dCBdt = k1 * CA - k2 * CB
    dCCdt = k2 * CB
    return np.array([dCAdt, dCBdt, dCCdt])


def stage1_noise(y, t):
    return np.diag(sigma1)


def stage2_drift(y, t, k3, k4):
    CA, CB, CC, CD, CE, CF = y
    dCAdt = 0
    dCBdt = -k3 * CB * CD**2
    dCCdt = -k4 * CC * CD**2
    dCDdt = -2 * k3 * CB * CD**2 - 2 * k4 * CC * CD**2
    dCEdt = k3 * CB * CD**2
    dCFdt = k4 * CC * CD**2
    return np.array([dCAdt, dCBdt, dCCdt, dCDdt, dCEdt, dCFdt])


def stage2_noise(y, t):
    return np.diag(sigma2)


def one_sde_simulation(data_type="training"):
    Ea1 = np.random.normal(Ea1_mean, CV * Ea1_mean)
    Ea2 = np.random.normal(Ea2_mean, CV * Ea2_mean)
    Ea3 = np.random.normal(Ea3_mean, CV * Ea3_mean)
    Ea4 = np.random.normal(Ea4_mean, CV * Ea4_mean)
    T1 = np.random.uniform(*T1_range)
    T2 = np.random.uniform(*T2_range_training) if data_type == "training" else np.random.uniform(*T2_range_testing)
    t1_seconds = np.random.uniform(*t1_range)
    t2_seconds = np.random.uniform(*t2_range)

    k1 = A1 * np.exp(-Ea1 / (R * T1))
    k2 = A2 * np.exp(-Ea2 / (R * T1))
    k3 = A3 * np.exp(-Ea3 / (R * T2))
    k4 = A4 * np.exp(-Ea4 / (R * T2))

    CA0_sample = np.random.normal(CA0, 0.05 * CA0)
    CD0_sample = np.random.normal(CD0, 0.05 * CD0)

    t1v = np.linspace(0, t1_seconds, 1000)
    y0_1 = np.array([CA0_sample, 0.0, 0.0])
    sol1 = sdeint.itoint(lambda y, t: stage1_drift(y, t, k1, k2), stage1_noise, y0_1, t1v)

    CA1f, CB1f, CC1f = sol1[-1]
    dilution = V1 / V2
    y0_2 = np.array([CA1f * dilution, CB1f * dilution, CC1f * dilution, CD0_sample, 0.0, 0.0])
    t2v = np.linspace(0, t2_seconds, 1000)
    sol2 = sdeint.itoint(lambda y, t: stage2_drift(y, t, k3, k4), stage2_noise, y0_2, t2v)

    params = dict(CA0_sample=CA0_sample, CD0_sample=CD0_sample, T1=T1, T2=T2,
                  t1_seconds=t1_seconds, t2_seconds=t2_seconds,
                  Ea1=Ea1, Ea2=Ea2, Ea3=Ea3, Ea4=Ea4, data_type=data_type)
    return (t1v / 60, sol1), (t2v / 60, sol2), params


def discrete_trajectories(all_stage1, all_stage2, noise_percentage=0.0035, sample_interval=0.25):
    """Same discretization convention as Data Generation.py / the author's
    notebook (sample_trajectories_discretely): noise sd = noise_percentage
    times the MEAN final concentration across all batches, per species."""
    final_c1 = [sol1[-1] for _, sol1 in all_stage1]
    mean1 = np.mean(final_c1, axis=0)
    noise1 = mean1 * noise_percentage
    discrete_stage1 = []
    for t1v, sol1 in all_stage1:
        t1k = np.arange(0, t1v[-1], sample_interval)
        out = np.zeros((len(t1k), 3))
        for j in range(3):
            interp = np.interp(t1k, t1v, sol1[:, j])
            out[:, j] = np.maximum(0, interp + np.random.normal(0, noise1[j], len(t1k)))
        discrete_stage1.append((t1k, out))

    final_c2 = [sol2[-1] for _, sol2 in all_stage2]
    mean2 = np.mean(final_c2, axis=0)
    noise2 = mean2 * noise_percentage
    discrete_stage2 = []
    for t2v, sol2 in all_stage2:
        t2k = np.arange(0, t2v[-1], sample_interval)
        out = np.zeros((len(t2k), 6))
        for j in range(6):
            interp = np.interp(t2k, t2v, sol2[:, j])
            out[:, j] = np.maximum(0, interp + np.random.normal(0, noise2[j], len(t2k)))
        discrete_stage2.append((t2k, out))
    return discrete_stage1, discrete_stage2


if __name__ == "__main__":
    print("Data_Generation_corrected.py defines the generator only -- it does not run or save anything.")
    print(f"sigma1 (stage 1, A/B/C) = {sigma1}")
    print(f"sigma2 (stage 2, A/B/C/D/E/F) = {sigma2}")
    print("Call one_sde_simulation(data_type) and discrete_trajectories(...) explicitly to generate data.")
