"""
Replication of Geremia, Marella et al. (2026) supplementary Tables S.3 and S.4
using the data generated by urethane_case_study.py.

TARGETS
  Table S.3  mechanistic-model parameters estimated from the 50 calibration
             batches: kref1, kref2, kref4, Ea1, Ea2, Ea4.
  Table S.4  mean absolute error for nC, nD, nE in calibration and validation,
             for three models: mechanistic, purely data-driven, hybrid.

MODELS, as described in [G] S.1.1-S.1.2
  mechanistic  the FP model (second reaction irreversible) with the six
               parameters estimated from the calibration data.
  data-driven  random forest, 150 trees, hyperparameters by 5-fold CV, using the
               process inputs fv1, fv2, T to predict nC, nD, nE directly.
  hybrid       random forest on the same inputs PLUS the mechanistic outputs
               nC, nD, nE ("knowledge augmentation").

TWO INFERENCES, both forced and both flagged
  1. Time is included as a regressor. [G] says the data-driven inputs are
     "fv1, fv2 and T ... over time". Without t the model is degenerate: during
     the long input plateaus fv1, fv2 and T are constant while nC keeps rising,
     so identical feature vectors would carry different targets.
  2. Parameter estimation weights each residual by 1/sigma of its measurement
     (maximum likelihood). [G] does not state a weighting, but nC ~ 0.8 mol,
     nD ~ 0.1 mol and nE ~ 1e-3 mol differ by three orders of magnitude, so an
     unweighted fit would ignore E entirely.
"""
import numpy as np
import pandas as pd
from scipy.integrate import solve_ivp
from scipy.optimize import least_squares
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, KFold
import warnings, time, json
warnings.filterwarnings('ignore')
import urethane_case_study as U

SEED = 7
SIGMA = U.NOISE_LEVELS                       # (nC, nD, nE) standard deviations

# ---------------------------------------------------------------- FP model with free parameters
def fp_rhs_theta(t, y, inputs, ic, th):
    """FP model (irreversible second reaction) with parameters th."""
    kref1, kref2, kref4, Ea1, Ea2, Ea4 = th
    nC, nD, nE = y
    fv1, fv2, T = inputs(t)
    n, V = U.closure(nC, nD, nE, fv1, fv2, ic)
    if V <= 0:
        return [0.0, 0.0, 0.0]
    cA, cB, cC = max(n[0], 0.0)/V, max(n[1], 0.0)/V, max(nC, 0.0)/V
    e = lambda Ea: np.exp(-Ea/U.R_GAS*(1.0/T - 1.0/U.TREF))
    k1, k2, k4 = kref1*1e-3*e(Ea1), kref2*1e-3*e(Ea2), kref4*1e-3*e(Ea4)
    r1, r2, r4 = k1*cA*cB, k2*cA*cC, k4*cA*cA
    return [V*(r1 - r2), V*r2, V*r4]

def sim_fp(th, inputs, ic, t):
    s = solve_ivp(fp_rhs_theta, (0.0, t[-1]), [0.0, 0.0, 0.0], t_eval=t,
                  args=(inputs, ic, th), method='LSODA', rtol=1e-8, atol=1e-11)
    if not s.success or s.y.shape[1] != len(t):
        return np.full((len(t), 3), np.nan)
    return s.y.T

# ---------------------------------------------------------------- estimation
# parameters are optimised as [log10 kref1, log10 kref2, log10 kref4, Ea/1e4]
TH0 = np.array([np.log10(U.KREF1), np.log10(U.KREF2), np.log10(U.KREF4),
                U.EA1/1e4, U.EA2/1e4, U.EA4/1e4])
LO = np.array([-6.0, -9.0, -10.0, 0.1, 0.1, 0.1])
HI = np.array([0.0, -2.0, -2.0, 15.0, 15.0, 15.0])

def unpack(z):
    return np.array([10**z[0], 10**z[1], 10**z[2], z[3]*1e4, z[4]*1e4, z[5]*1e4])

# Residual weighting. [G] does not state one. Evidence settles it: an unweighted
# fit reproduces the paper's mechanistic MAE for C to within 1.5% (calibration
# 4.216e-2 vs 4.280e-2; validation 4.146e-2 vs 4.370e-2) and recovers Ea1 to 0.3%
# and Ea4 to 0%, whereas 1/sigma weighting misses C by a factor 2.3. So the paper
# fitted unweighted; that is used here, with the alternative kept for inspection.
WEIGHT_BY_SIGMA = False

def fit_parameters(inputs, meas, ic, t, verbose=True):
    w = 1.0/SIGMA if WEIGHT_BY_SIGMA else np.ones(3)
    n_eval = [0]
    def resid(z):
        th = unpack(z)
        out = []
        for i, f in enumerate(inputs):
            pred = sim_fp(th, f, ic, t)
            if not np.isfinite(pred).all():
                return np.full(meas.size, 1e6)
            out.append(((pred - meas[i])*w).ravel())
        n_eval[0] += 1
        r = np.concatenate(out)
        if verbose and n_eval[0] % 10 == 0:
            print(f"    eval {n_eval[0]:4d}  cost {0.5*np.sum(r**2):.6e}", flush=True)
        return r
    r = least_squares(resid, TH0, bounds=(LO, HI), xtol=1e-10, ftol=1e-10,
                      x_scale='jac', max_nfev=400)
    return unpack(r.x), float(r.cost)

# ---------------------------------------------------------------- feature matrices
def features(inputs, t, mech=None):
    """Rows are (batch, time) pairs. Columns: t, fv1, fv2, T [, mech nC/nD/nE]."""
    rows = []
    for i, f in enumerate(inputs):
        for j, tj in enumerate(t):
            fv1, fv2, T = f(tj)
            base = [tj, fv1, fv2, T]
            if mech is not None:
                base += list(mech[i][j])
            rows.append(base)
    return np.asarray(rows)

def flatten_targets(Y):
    return Y.reshape(-1, 3)

def mae_by_species(pred, obs):
    return np.abs(pred - obs).mean(axis=0)

# ================================================================= run
if __name__ == '__main__':
    t0 = time.time()
    print("generating the same datasets as urethane_case_study.py ...", flush=True)
    t, inp_c, meas_c, clean_c, fp_nom_c, ic = U.generate(U.N_CALIBRATION, 101)
    _, inp_v, meas_v, clean_v, fp_nom_v, _ = U.generate(U.N_VALIDATION, 202)
    print(f"  calibration {meas_c.shape}   validation {meas_v.shape}   "
          f"({time.time()-t0:.0f}s)\n", flush=True)

    # ---------------- Table S.3 : parameter estimation ----------------
    print("estimating the six mechanistic parameters on the calibration set ...", flush=True)
    th, cost = fit_parameters(inp_c, meas_c, ic, t)
    paper = dict(kref1=1.57e-3, kref2=8.17e-6, kref4=3.38e-7,
                 Ea1=6.27e4, Ea2=2.77e4, Ea4=1.16e4)
    truth = dict(kref1=U.KREF1, kref2=U.KREF2, kref4=U.KREF4,
                 Ea1=U.EA1, Ea2=U.EA2, Ea4=U.EA4)
    names = ['kref1', 'kref2', 'kref4', 'Ea1', 'Ea2', 'Ea4']
    t3 = pd.DataFrame({'parameter': names,
                       'true (Table S.2)': [truth[n] for n in names],
                       'this work': th,
                       'paper (Table S.3)': [paper[n] for n in names]})
    print("\n=== Table S.3 : mechanistic model parameters ===")
    print(t3.to_string(index=False, float_format=lambda v: f'{v:.4g}'))
    print(f"  weighted least-squares cost {cost:.6e}   ({time.time()-t0:.0f}s)\n", flush=True)

    # ---------------- mechanistic predictions with the fitted parameters -------
    mech_c = np.array([sim_fp(th, f, ic, t) for f in inp_c])
    mech_v = np.array([sim_fp(th, f, ic, t) for f in inp_v])

    # ---------------- data-driven and hybrid random forests -------------------
    grid = {'max_depth': [None, 12, 20], 'min_samples_leaf': [1, 2, 5]}
    cv = KFold(5, shuffle=True, random_state=SEED)
    models = {}
    for tag, mc, mv in [('data-driven', None, None), ('hybrid', mech_c, mech_v)]:
        Xtr = features(inp_c, t, mc)
        Xte = features(inp_v, t, mv)
        ytr = flatten_targets(meas_c)
        gs = GridSearchCV(RandomForestRegressor(n_estimators=150, random_state=SEED, n_jobs=-1),
                          grid, cv=cv, scoring='neg_mean_absolute_error', n_jobs=1)
        gs.fit(Xtr, ytr)
        models[tag] = dict(best=gs.best_params_,
                           cal=gs.best_estimator_.predict(Xtr).reshape(meas_c.shape),
                           val=gs.best_estimator_.predict(Xte).reshape(meas_v.shape))
        print(f"  {tag:12s} RF hyperparameters {gs.best_params_}  ({time.time()-t0:.0f}s)", flush=True)

    # ---------------- Table S.4 : MAE comparison ------------------------------
    rows = []
    for tag, pc, pv in [('Mechanistic', mech_c, mech_v),
                        ('Data-driven', models['data-driven']['cal'], models['data-driven']['val']),
                        ('Hybrid', models['hybrid']['cal'], models['hybrid']['val'])]:
        mc = mae_by_species(pc.reshape(-1, 3), meas_c.reshape(-1, 3))
        mv = mae_by_species(pv.reshape(-1, 3), meas_v.reshape(-1, 3))
        rows.append(dict(model=tag, cal_C=mc[0], cal_D=mc[1], cal_E=mc[2],
                         val_C=mv[0], val_D=mv[1], val_E=mv[2]))
    t4 = pd.DataFrame(rows).set_index('model')
    paper_t4 = pd.DataFrame({
        'cal_C': [4.28e-2, 1.86e-2, 7.01e-3], 'cal_D': [2.90e-2, 2.65e-2, 3.94e-3],
        'cal_E': [6.34e-4, 4.66e-4, 1.46e-4], 'val_C': [4.37e-2, 4.12e-2, 1.72e-2],
        'val_D': [3.05e-2, 7.08e-2, 9.44e-3], 'val_E': [8.50e-4, 1.08e-3, 4.56e-4]},
        index=['Mechanistic', 'Data-driven', 'Hybrid'])

    pd.set_option('display.width', 200)
    fmt = lambda v: f'{v:.3e}'
    print("\n=== Table S.4 : MAE [mol] -- THIS WORK ===")
    print(t4.to_string(float_format=fmt))
    print("\n=== Table S.4 : MAE [mol] -- PAPER ===")
    print(paper_t4.to_string(float_format=fmt))
    print("\n=== ratio (this work / paper) ===")
    print((t4/paper_t4).to_string(float_format=lambda v: f'{v:.2f}'))

    imp = pd.DataFrame({
        'over mechanistic': 100*(1 - t4.loc['Hybrid']/t4.loc['Mechanistic']),
        'over data-driven': 100*(1 - t4.loc['Hybrid']/t4.loc['Data-driven'])})
    imp_paper = pd.DataFrame({
        'over mechanistic': [84, 86, 77, 61, 69, 46],
        'over data-driven': [62, 85, 69, 58, 87, 58]}, index=t4.columns)
    print("\n=== hybrid improvement [%] : this work | paper ===")
    print(imp.join(imp_paper, rsuffix=' (paper)').to_string(float_format=lambda v: f'{v:.0f}'))

    with pd.ExcelWriter('urethane_replication.xlsx') as w:
        t3.to_excel(w, sheet_name='TableS3', index=False)
        t4.to_excel(w, sheet_name='TableS4_thiswork')
        paper_t4.to_excel(w, sheet_name='TableS4_paper')
        imp.join(imp_paper, rsuffix=' (paper)').to_excel(w, sheet_name='improvement')
    json.dump({n: float(v) for n, v in zip(names, th)},
              open('urethane_fitted_params.json', 'w'), indent=2)
    print(f"\nSaved urethane_replication.xlsx and urethane_fitted_params.json "
          f"({time.time()-t0:.0f}s)")
